"""Export reproducible lecture data from the actual Python evaluators (no JS solver)."""

import argparse
import hashlib
import json
from dataclasses import replace
from pathlib import Path

from mech_design.case import load_case
from mech_design.evaluation import evaluate

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / "docs/learning/assets/lecture-data.js"
LECTURE = ROOT / "docs/learning/01-lecture.md"
START = "<!-- BEGIN GENERATED COMPARISON -->"
END = "<!-- END GENERATED COMPARISON -->"


def build_data() -> dict:
    case = load_case(ROOT / "cases/heated_cantilever.toml")
    sources = [ROOT / "cases/heated_cantilever.toml"] + [
        ROOT / "src/mech_design" / name for name in ("case.py", "models.py", "evaluation.py")
    ]
    # Normalize line endings so the provenance digest is portable across Git checkouts.
    digest = hashlib.sha256("\n".join(p.read_text(encoding="utf-8") for p in sources).encode())
    scenarios = {}
    for width_mm in (15, 30, 45, 60):
        for half_mm in range(4, 13):
            thickness_mm = half_mm / 2
            variant = replace(
                case,
                beam=replace(
                    case.beam,
                    width_m=width_mm / 1000,
                    thickness_m=thickness_mm / 1000,
                ),
            )
            report = evaluate(variant)
            scenarios[f"{width_mm}:{thickness_mm:g}"] = {
                "mass_kg": report["mass_kg"],
                "overall_status": report["overall_status"],
                "metrics": {
                    r["metric"]: r for r in report["evaluations"] if r["value"] is not None
                },
                "unevaluated_count": sum(
                    r["status"] == "not_evaluated" for r in report["evaluations"]
                ),
            }
    return {
        "schema_version": 1,
        "source_digest": digest.hexdigest(),
        "baseline_input": evaluate(case)["input"],
        "scenarios": scenarios,
    }


def comparison(data: dict) -> str:
    base = data["scenarios"]["30:3"]
    thin = data["scenarios"]["30:2"]
    rows = [
        "| 指標 | 板厚3 mm | 板厚2 mm | 学習用制約 |",
        "|---|---:|---:|---|",
        f"| 質量 | {base['mass_kg'] * 1000:.2f} g | {thin['mass_kg'] * 1000:.2f} g | 上限未設定 |",
    ]
    for key, label, factor, unit, digits, limit in (
        ("root_stress", "公称曲げ応力", 1e-6, "MPa", 3, "30 MPa以下"),
        ("tip_deflection", "先端たわみ", 1000, "mm", 4, "0.1 mm以下"),
        ("first_frequency", "一次固有振動数", 1, "Hz", 2, "200 Hz以上"),
        ("tip_temperature", "先端温度", 1, "K", 2, "313.15 K以下"),
    ):
        a, b = base["metrics"][key], thin["metrics"][key]
        states = {"pass": "合格", "fail": "違反"}
        rows.append(
            f"| {label} | {a['value'] * factor:.{digits}f} {unit}（{states[a['status']]}）"
            f" | {b['value'] * factor:.{digits}f} {unit}（{states[b['status']]}） | {limit} |"
        )
    return "\n".join(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = build_data()
    script = "// Generated by scripts/build_lecture_data.py; do not edit.\n"
    script += (
        "window.MECH_LECTURE_DATA = "
        + json.dumps(data, ensure_ascii=True, indent=2, allow_nan=False)
        + ";\n"
    )
    lecture = LECTURE.read_text(encoding="utf-8")
    if lecture.count(START) != 1 or lecture.count(END) != 1:
        raise ValueError("Lecture must contain one comparison marker pair")
    before, rest = lecture.split(START)
    _, after = rest.split(END)
    updated = before + START + "\n" + comparison(data) + "\n" + END + after
    changes = [(DESTINATION, script), (LECTURE, updated)]
    if args.check:
        stale = [
            str(p.relative_to(ROOT))
            for p, content in changes
            if not p.exists() or p.read_text(encoding="utf-8") != content
        ]
        if stale:
            print("Stale lecture data: " + ", ".join(stale))
            return 1
        print("Lecture data and comparison table match the Python models.")
        return 0
    for path, content in changes:
        path.write_text(content, encoding="utf-8", newline="\n")
    print("Generated 36 lecture scenarios and the comparison table.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
